#define VERTEX_SHADER
#define _CV_VERTEX_DEFAULT
#define VANILLA_LIGHTING
#define ANIMATED_FOLIAGE
#define SHADOW_MAP_PRESENT
#define SHADOW_MAP_SIZE 1024
#define COLORED_LIGHTS_ENABLED
#define LIGHT_VOLUME_SIZE vec3(256.0)
#define MATERIAL_TARGET_UNKNOWN
//#define DEPTH_PASS
//#define PBR_ENABLED
