#define VERTEX_SHADER
#define _CV_VERTEX_DEFAULT
#define VANILLA_LIGHTING
#define ANIMATED_FOLIAGE
#define SHADOW_MAP_PRESENT
#define SHADOW_MAP_SIZE 1024
#define MATERIAL_TARGET_UNKNOWN
//#define DEPTH_PASS
//#define PBR_ENABLED
#define _CV_GLINT_STRENGTH vec2(1.0)
